// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-eOlMYh-ujsj8Mb6afpK0SBnSOk3MfX0',
    appId: '1:900790491091:web:13e4f359426cd79a088126',
    messagingSenderId: '900790491091',
    projectId: 'blockbloomgame',
    authDomain: 'blockbloomgame.firebaseapp.com',
    storageBucket: 'blockbloomgame.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2tQECcLoENf2DuNMK6T3TPPjKbk6kUlA',
    appId: '1:900790491091:android:628b24c7d6f33f9b088126',
    messagingSenderId: '900790491091',
    projectId: 'blockbloomgame',
    storageBucket: 'blockbloomgame.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9WAyikgzZGgC-ZUOU5NirrUSJzzKAFho',
    appId: '1:900790491091:ios:805210eab8a70f06088126',
    messagingSenderId: '900790491091',
    projectId: 'blockbloomgame',
    storageBucket: 'blockbloomgame.firebasestorage.app',
    iosBundleId: 'com.example.blockBloom',
  );
}
